all_departments = [
    {'id': 1, 'name': 'ANESTHESIOLOGY'},
    {'id': 2, 'name': 'CARDIOLOGY'},
    {'id': 3, 'name': 'CARDIOVASCULAR'},
    {'id': 4, 'name': 'CSP'},
    {'id': 5, 'name': 'EMERGENCY MEDICINE'}
]

all_grant_admins = [
    {'id': 1, 'name': 'MARX,GROUCHO', 'email': 'groucho@umich.edu'},
    {'id': 2, 'name': 'MARX,HARPO', 'email': 'harpo@umich.edu'},
    {'id': 3, 'name': 'MARX,CHICO', 'email': 'chico@umich.edu'},
    {'id': 4, 'name': 'MARX,ZEPPO', 'email': ''}
]

employees = [
    {
        'id': 106,
        'name': 'EMP 106',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'org': 'CCMR',
        'email': 'emp106@va.gov',
        'nonva_email': 'emp106@gmail.com',
        'salary': None,
        'fringe': None,
        'active': 1
    },
    {
        'id': 107,
        'name': 'EMP 107',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'org': 'CCMR',
        'email': 'emp107@va.gov',
        'nonva_email': 'emp107@gmail.com',
        'salary': 74971,
        'fringe': 46.0,
        'active': 1
    },
    {
        'id': 15,
        'name': 'EMP 15',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'org': 'CCMR',
        'email': 'emp15@va.gov',
        'nonva_email': 'emp15@gmail.com',
        'salary': 52239,
        'fringe': 38.8,
        'active': 1
    },
    {
        'id': 20,
        'name': 'EMP 20',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'org': 'CCMR',
        'email': 'emp20@va.gov',
        'nonva_email': 'emp20@gmail.com',
        'salary': 61965,
        'fringe': 35.7,
        'active': 1
    },
    {
        'id': 211,
        'name': 'EMP 211',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'org': 'CCMR',
        'email': 'emp211@va.gov',
        'nonva_email': 'emp211@gmail.com',
        'salary': 50657,
        'fringe': 22.9,
        'active': 1
    },
    {
        'id': 264,
        'name': 'EMP 264',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'org': 'CCMR',
        'email': 'emp264@va.gov',
        'nonva_email': 'emp264@gmail.com',
        'salary': 70286,
        'fringe': 26.1,
        'active': 1
    },
    {
        'id': 282,
        'name': 'EMP 282',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'org': 'CCMR',
        'email': 'emp282@va.gov',
        'nonva_email': 'emp282@gmail.com',
        'salary': 44444,
        'fringe': 4.4,
        'active': 1
    },
    {
        'id': 52,
        'name': 'EMP 52',
        'fte': 50,
        'investigator': 0,
        'intern': 0,
        'org': 'CCMR',
        'email': 'emp52@va.gov',
        'nonva_email': 'emp52@gmail.com',
        'salary': 104971,
        'fringe': 33.5,
        'active': 1
    },
    {
        'id': 56,
        'name': 'EMP 56',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'org': 'CCMR',
        'email': 'emp56@va.gov',
        'nonva_email': 'emp56@gmail.com',
        'salary': 74971,
        'fringe': 43.9,
        'active': 1
    },
    {
        'id': 61,
        'name': 'EMP 61',
        'fte': 0,
        'investigator': 1,
        'intern': 0,
        'org': 'CCMR',
        'email': 'emp61@va.gov',
        'nonva_email': 'emp61@gmail.com',
        'salary': None,
        'fringe': None,
        'active': 1
    },
    {
        'id': 62,
        'name': 'EMP 62',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'org': 'CCMR',
        'email': 'emp62@va.gov',
        'nonva_email': 'emp62@gmail.com',
        'salary': 53822,
        'fringe': 7.7,
        'active': 1
    },
    {
        'id': 73,
        'name': 'EMP 73',
        'fte': 62,
        'investigator': 1,
        'intern': 0,
        'org': 'CCMR',
        'email': 'emp73@va.gov',
        'nonva_email': 'emp73@gmail.com',
        'salary': 114786,
        'fringe': 35.2,
        'active': 1
    },
    {
        'id': 76,
        'name': 'EMP 76',
        'fte': 63,
        'investigator': 1,
        'intern': 0,
        'org': 'CCMR',
        'email': 'emp76@va.gov',
        'nonva_email': 'emp76@gmail.com',
        'salary': 142052,
        'fringe': 31.7,
        'active': 1
    },
]

# Note: assignments are monthly
billable_assignments = [
    {
        'id': 2271,
        'employee_id': 282,
        'employee': 'EMP 282',
        'project_id': 297,
        'project': 'Prj 297',
        'frum': '1910',
        'thru': '1912',
        'effort': 45,
        'active': 1
    },
    {
        'id': 2272,
        'employee_id': 52,
        'employee': 'EMP 52',
        'project_id': 297,
        'project': 'Prj 297',
        'frum': '1910',
        'thru': '1911',
        'effort': 10,
        'active': 1
    },
    {
        'id': 2275,
        'employee_id': 56,
        'employee': 'EMP 56',
        'project_id': 299,
        'project': 'Prj 299',
        'frum': '2002',
        'thru': '2003',
        'effort': 45,
        'active': 1
    },
    {
        'id': 2282,
        'employee_id': 61,
        'employee': 'EMP 61',
        'project_id': 299,
        'project': 'Prj 299',
        'frum': '1907',
        'thru': '2106',
        'effort': 10,
        'active': 1
    },
    {
        'id': 2283,
        'employee_id': 73,
        'employee': 'EMP 73',
        'project_id': 315,
        'project': 'Prj 315',
        'frum': '1912',
        'thru': '2002',
        'effort': 10,
        'active': 1
    },
    {
        'id': 2365,
        'employee_id': 106,
        'employee': 'EMP 106',
        'project_id': 309,
        'project': 'Prj 309',
        'frum': '1910',
        'thru': '2009',
        'effort': 5,
        'active': 1
    },
    {
        'id': 2375,
        'employee_id': 107,
        'employee': 'EMP 107',
        'project_id': 309,
        'project': 'Prj 309',
        'frum': '2002',
        'thru': '2009',
        'effort': 15,
        'active': 1
    },
    {
        'id': 2382,
        'employee_id': 76,
        'employee': 'EMP 76',
        'project_id': 309,
        'project': 'Prj 309',
        'frum': '2002',
        'thru': '2002',
        'effort': 10,
        'active': 1
    },
    {
        'id': 2396,
        'employee_id': 282,
        'employee': 'EMP 282',
        'project_id': 315,
        'project': 'Prj 315',
        'frum': '1909',
        'thru': '1912',
        'effort': 20,
        'active': 1
    },
]

# Note: ledger entries are quarterly
ledger_rex = [
    {
        'id': 1,
        'quarter': '20201',
        'dept': 'HEMATOLOGY',
        'admin_approved': False,
        'va_approved': True,
        'invoice_num': 'K0H1001',
        'asn_id': 2271,
        'project': 'Prj 297',
        'employee': 'EMP 282',
        'salary': 44444,
        'fringe': 14.4,
        'total_day': 194.9,
        'frum': '1910',
        'thru': '1912',
        'effort': 45,
        'days': 92,
        'amount': 6076.94,
        'paid': False,
        'balance': 6076.94,
        'short_code': '123456',
        'grant_admin': 'MARX,GROUCHO',
        'grant_admin_email': 'groucho@umich.edu'
    },
    {
        'id': 2,
        'quarter': '20201',
        'dept': '',
        'admin_approved': False,
        'va_approved': False,
        'invoice_num': '',
        'asn_id': 2272,
        'project': 'Prj 297',
        'employee': 'EMP 52',
        'salary': 104971,
        'fringe': 33.3,
        'total_day': 194.9,
        'frum': '1910',
        'thru': '1911',
        'effort': 10,
        'days': 61,
        'amount': 8068.76,
        'paid': False,
        'balance': 8068.76,
        'short_code': '',
        'grant_admin': '',
        'grant_admin_email': ''
    },
    {
        'id': 3,
        'quarter': '20201',
        'dept': 'EPIDEMIOLOGY',
        'admin_approved': False,
        'va_approved': False,
        'invoice_num': 'K0H1003',
        'asn_id': 2282,
        'project': 'Prj 299',
        'employee': 'EMP 61',
        'salary': None,
        'fringe': None,
        'total_day': None,
        'frum': '1907',
        'thru': '2106',
        'effort': 10,
        'days': 92,
        'amount': None,
        'paid': False,
        'balance': None,
        'short_code': '55667788',
        'grant_admin': 'MARX,CHICO',
        'grant_admin_email': 'chico@umich.edu'
    }
]
