from models.project import Project
from models.employee import Employee
from models.assignment import Assignment
from models.ledger import Ledger
from models.department import Department
from models.grant_admin import GrantAdmin


projects = [
    Project({
        'id': 297,
        'name': 'Prj 297',
        'full_name': 'Prj Full Name 297',
        'frum': '1901',
        'thru': '1912',
        'active': 1,
        'non_va': 1
    }),
    Project({
        'id': 298,
        'name': 'Prj 298',
        'full_name': 'Prj Full Name 298',
        'frum': '1907',
        'thru': '2406',
        'active': 1,
        'non_va': 0
    }),
    Project({
        'id': 299,
        'name': 'Prj 299',
        'full_name': 'Prj Full Name 299',
        'frum': '1907',
        'thru': '2106',
        'active': 1,
        'non_va': 1
    }),
    Project({
        'id': 301,
        'name': 'Prj 301',
        'full_name': 'Prj Full Name 301',
        'frum': '1904',
        'thru': '1909',
        'active': 1,
        'non_va': 0
    }),
    Project({
        'id': 309,
        'name': 'Prj 309',
        'full_name': 'Prj Full Name 309',
        'frum': '1908',
        'thru': '2009',
        'active': 1,
        'non_va': 1
    }),
    Project({
        'id': 311,
        'name': 'Prj 311',
        'full_name': 'Prj Full Name 311',
        'frum': '1910',
        'thru': '2009',
        'active': 1,
        'non_va': 0
    }),
    Project({
        'id': 312,
        'name': 'Prj 312',
        'full_name': 'Prj Full Name 312',
        'frum': '1909',
        'thru': '2109',
        'active': 1,
        'non_va': 0
    }),
    Project({
        'id': 315,
        'name': 'Prj 315',
        'full_name': 'Prj Full Name 315',
        'frum': '1807',
        'thru': '2106',
        'active': 1,
        'non_va': 1
    })
]

employees = [
    Employee({
        'id': 44,
        'name': 'AARON,HENRY',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'pm': 0,
        'org': 'CCMR',
        'va_email': 'aaron44@va.gov',
        'nonva_email': 'aaron44@gmail.com',
        'salary': 74971,
        'fringe': 46.0,
        'notes': 'Aaron note',
        'active': 1
    }),
    Employee({
        'id': 14,
        'name': 'BANKS,ERNEST',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'pm': 0,
        'org': 'CCMR',
        'va_email': None,
        'nonva_email': None,
        'salary': 44444,
        'fringe': 4.4,
        'notes': None,
        'active': 1
    }),
    Employee({
        'id': 8,
        'name': 'BERRA,YOGI',
        'fte': 80,
        'investigator': 0,
        'intern': 0,
        'pm': 1,
        'org': 'CCMR',
        'va_email': None,
        'nonva_email': None,
        'salary': 53822,
        'fringe': 7.7,
        'notes': None,
        'active': 1
    }),
    Employee({
        'id': 5,
        'name': 'DIMAGGIO,JOSEPH P',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'pm': 1,
        'org': 'CCMR',
        'va_email': 'dimaggio5@va.gov',
        'nonva_email': 'dimaggio5@umich.edu',
        'salary': 74971,
        'fringe': 43.9,
        'notes': None,
        'active': 1
    }),
    Employee({
        'id': 16,
        'name': 'FORD,WHITEY',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'pm': 1,
        'org': 'CCMR',
        'va_email': 'ford16@va.gov',
        'nonva_email': None,
        'salary': 70286,
        'fringe': 26.1,
        'notes': None,
        'active': 1
    }),
    Employee({
        'id': 4,
        'name': 'GEHRIG,HENRY LOUIS',
        'fte': 50,
        'investigator': 1,
        'intern': 0,
        'pm': 0,
        'org': 'SMITREC',
        'va_email': None,
        'nonva_email': 'gehrig@umich.edu',
        'salary': 104971,
        'fringe': 33.5,
        'notes': 'Gehrig note',
        'active': 1
    }),
    Employee({
        'id': 2,
        'name': 'JETER,DEREK',
        'fte': 100,
        'investigator': 0,
        'intern': 1,
        'pm': 0,
        'org': 'CCMR',
        'va_email': 'jeter2@va.gov',
        'nonva_email': None,
        'salary': 52239,
        'fringe': 38.8,
        'notes': 'Intern',
        'active': 1
    }),
    Employee({
        'id': 6,
        'name': 'KALINE,ALBERT W',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'pm': 0,
        'org': 'CCMR',
        'va_email': 'kaline6@va.gov',
        'nonva_email': 'kaline6@gmail.com',
        'salary': None,
        'fringe': None,
        'notes': 'Kaline note',
        'active': 1
    }),
    Employee({
        'id': 32,
        'name': 'KOUFAX,SANFORD',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'pm': 1,
        'org': 'CCMR',
        'va_email': 'koufax32@va.gov',
        'nonva_email': 'koufax32@yahoo.com',
        'salary': 50657,
        'fringe': 22.9,
        'notes': None,
        'active': 1
    }),
    Employee({
        'id': 7,
        'name': 'MANTLE,MICKEY',
        'fte': 0,
        'investigator': 1,
        'intern': 0,
        'pm': 0,
        'org': 'CCMR',
        'va_email': 'mantle7@va.gov',
        'nonva_email': None,
        'salary': None,
        'fringe': None,
        'notes': None,
        'active': 1
    }),
    Employee({
        'id': 24,
        'name': 'MAYS,WILLIE HOWARD JR',
        'fte': 63,
        'investigator': 1,
        'intern': 0,
        'pm': 0,
        'org': 'CCMR',
        'va_email': None,
        'nonva_email': None,
        'salary': 142052,
        'fringe': 31.7,
        'notes': None,
        'active': 1
    }),
    Employee({
        'id': 3,
        'name': 'RUTH,BABE',
        'fte': 100,
        'investigator': 0,
        'intern': 0,
        'pm': 1,
        'org': 'CCMR',
        'va_email': None,
        'nonva_email': None,
        'salary': 61965,
        'fringe': 35.7,
        'notes': None,
        'active': 1
    }),
    Employee({
        'id': 9,
        'name': 'WILLIAMS,THEODORE',
        'fte': 62,
        'investigator': 1,
        'intern': 0,
        'pm': 0,
        'org': 'RCA',
        'va_email': None,
        'nonva_email': 'williams9@umich.edu',
        'salary': 114786,
        'fringe': 35.2,
        'notes': None,
        'active': 1
    }),
]

assignments = [
    Assignment({
        'id': 2271,
        'employee_id': 14,
        'employee': 'BANKS,ERNEST',
        'project_id': 297,
        'project': 'Prj 297',
        'frum': '1910',
        'thru': '1912',
        'effort': 45,
        'notes': 'Asn 2271 note',
        'active': 1
    }),
    Assignment({
        'id': 2272,
        'employee_id': 4,
        'employee': 'GEHRIG,HENRY LOUIS',
        'project_id': 297,
        'project': 'Prj 297',
        'frum': '1910',
        'thru': '1912',
        'effort': 10,
        'notes': None,
        'active': 1
    }),
    Assignment({
        'id': 2275,
        'employee_id': 5,
        'employee': 'DIMAGGIO,JOSEPH P',
        'project_id': 299,
        'project': 'Prj 299',
        'frum': '2002',
        'thru': '2003',
        'effort': 45,
        'notes': None,
        'active': 1
    }),
    Assignment({
        'id': 2282,
        'employee_id': 7,
        'employee': 'MANTLE,MICKEY',
        'project_id': 299,
        'project': 'Prj 299',
        'frum': '1909',
        'thru': '1911',
        'effort': 10,
        'notes': 'Asn 2282 note',
        'active': 1
    }),
    Assignment({
        'id': 2283,
        'employee_id': 9,
        'employee': 'WILLIAMS,THEODORE',
        'project_id': 315,
        'project': 'Prj 315',
        'frum': '1912',
        'thru': '2002',
        'effort': 10,
        'notes': None,
        'active': 1
    }),
    Assignment({
        'id': 2365,
        'employee_id': 6,
        'employee': 'KALINE,ALBERT W',
        'project_id': 309,
        'project': 'Prj 309',
        'frum': '1910',
        'thru': '2009',
        'effort': 5,
        'notes': None,
        'active': 1
    }),
    Assignment({
        'id': 2375,
        'employee_id': 44,
        'employee': 'AARON,HENRY',
        'project_id': 309,
        'project': 'Prj 309',
        'frum': '2002',
        'thru': '2009',
        'effort': 15,
        'notes': None,
        'active': 1
    }),
    Assignment({
        'id': 2382,
        'employee_id': 24,
        'employee': 'MAYS,WILLIE HOWARD JR',
        'project_id': 309,
        'project': 'Prj 309',
        'frum': '2002',
        'thru': '2002',
        'effort': 10,
        'notes': 'Yawn',
        'active': 1
    }),
    Assignment({
        'id': 2396,
        'employee_id': 14,
        'employee': 'BANKS,ERNEST',
        'project_id': 315,
        'project': 'Prj 315',
        'frum': '1910',
        'thru': '2009',
        'effort': 20,
        'notes': 'Burp',
        'active': 1
    })
]

dept_objs = [
    Department({'id': 2, 'name': 'ANESTHESIOLOGY'}),
    Department({'id': 1, 'name': 'CARDIOLOGY'}),
    Department({'id': 4, 'name': 'CSP'}),
    Department({'id': 5, 'name': 'EMERGENCY MEDICINE'}),
    Department({'id': 3, 'name': 'VERAM'}),
]

grant_admin_objs = [
    GrantAdmin({'id': 3, 'name': 'MARX,CHICO', 'email': 'chico@umich.edu'}),
    GrantAdmin({'id': 1, 'name': 'MARX,GROUCHO', 'email': 'groucho@umich.edu'}),
    GrantAdmin({'id': 2, 'name': 'MARX,HARPO', 'email': 'harpo@umich.edu'}),
    GrantAdmin({'id': 4, 'name': 'MARX,ZEPPO', 'email': None})
]

ledger_objs = [
    Ledger({
        'id': 1,
        'quarter': 20201,
        'dept': 'HEMATOLOGY',
        'admin_approved': 0,
        'va_approved': 1,
        'invoice_num': 'K0H1001',
        'asn_id': 2271,
        'project': 'Prj 297',
        'employee': 'BANKS,ERNEST',
        'salary': 44444,
        'fringe': 4.4,
        'total_day': 177.86,
        'frum': '1910',
        'thru': '1912',
        'effort': 45,
        'days': 92,
        'amount': 7363.45,
        'paid': 0,
        'balance': 7363.45,
        'short_code': '123456',
        'grant_admin': 'MARX,GROUCHO',
        'grant_admin_email': 'groucho@umich.edu'
    }),
    Ledger({
        'id': 2,
        'quarter': 20201,
        'dept': None,
        'admin_approved': 0,
        'va_approved': 0,
        'invoice_num': None,
        'asn_id': 2272,
        'project': 'Prj 297',
        'employee': 'GEHRIG,HENRY LOUIS',
        'salary': 104971,
        'fringe': 33.5,
        'total_day': 537.18,
        'frum': '1910',
        'thru': '1912',
        'effort': 10,
        'days': 92,
        'amount': 4942.04,
        'paid': 0,
        'balance': 4942.04,
        'short_code': None,
        'grant_admin': None,
        'grant_admin_email': None
    }),
    Ledger({
        'id': 3,
        'quarter': 20201,
        'dept': 'EPIDEMIOLOGY',
        'admin_approved': 0,
        'va_approved': 0,
        'invoice_num': 'K0H1003',
        'asn_id': 2282,
        'project': 'Prj 299',
        'employee': 'MANTLE,MICKEY',
        'salary': None,
        'fringe': None,
        'total_day': None,
        'frum': '1910',
        'thru': '1911',
        'effort': 10,
        'days': 61,
        'amount': None,
        'paid': False,
        'balance': None,
        'short_code': '556677',
        'grant_admin': 'MARX,CHICO',
        'grant_admin_email': 'chico@umich.edu'
    })
]

department_items = [
    '',
    'ANESTHESIOLOGY',
    'CARDIOLOGY',
    'CSP',
    'EMERGENCY MEDICINE',
    'VERAM'
]

grant_admin_items = [
    '',
    'MARX,CHICO',
    'MARX,GROUCHO',
    'MARX,HARPO',
    'MARX,ZEPPO'
]

ledger_items_qtr_1 = [
    Ledger({
        'id': 1,
        'quarter': 20201,
        'dept': 'HEMATOLOGY',
        'admin_approved': 0,
        'va_approved': 1,
        'invoice_num': 'K0H1001',
        'asn_id': 2271,
        'project': 'Prj 297',
        'employee': 'BANKS,ERNEST',
        'salary': 44444,
        'fringe': 4.4,
        'total_day': 177.86,
        'frum': '1910',
        'thru': '1912',
        'effort': 45,
        'days': 92,
        'amount': 7363.45,
        'paid': 0,
        'balance': 7363.45,
        'short_code': '123456',
        'grant_admin': 'MARX,GROUCHO',
        'grant_admin_email': 'groucho@umich.edu'
    }),
    Ledger({
        'id': 2,
        'quarter': 20201,
        'dept': None,
        'admin_approved': 0,
        'va_approved': 0,
        'invoice_num': None,
        'asn_id': 2272,
        'project': 'Prj 297',
        'employee': 'GEHRIG,HENRY LOUIS',
        'salary': 104971,
        'fringe': 33.5,
        'total_day': 537.18,
        'frum': '1910',
        'thru': '1912',
        'effort': 10,
        'days': 92,
        'amount': 4942.04,
        'paid': 0,
        'balance': 4942.04,
        'short_code': None,
        'grant_admin': None,
        'grant_admin_email': None
    }),
    Ledger({
        'id': 3,
        'quarter': 20201,
        'dept': 'EPIDEMIOLOGY',
        'admin_approved': 0,
        'va_approved': 0,
        'invoice_num': 'K0H1003',
        'asn_id': 2282,
        'project': 'Prj 299',
        'employee': 'MANTLE,MICKEY',
        'salary': None,
        'fringe': None,
        'total_day': None,
        'frum': '1910',
        'thru': '1911',
        'effort': 10,
        'days': 61,
        'amount': None,
        'paid': 0,
        'balance': None,
        'short_code': '556677',
        'grant_admin': 'MARX,CHICO',
        'grant_admin_email': 'chico@umich.edu'
    }),
    Ledger({
        'id': None,
        'quarter': 20201,
        'dept': None,
        'admin_approved': 0,
        'va_approved': 0,
        'invoice_num': None,
        'asn_id': 2365,
        'project': 'Prj 309',
        'employee': 'KALINE,ALBERT W',
        'salary': None,
        'fringe': None,
        'total_day': None,
        'frum': '1910',
        'thru': '1912',
        'effort': 5,
        'days': 92,
        'amount': None,
        'paid': 0,
        'balance': None,
        'short_code': None,
        'grant_admin': None,
        'grant_admin_email': None
    }),
    Ledger({
        'id': None,
        'quarter': 20201,
        'dept': None,
        'admin_approved': 0,
        'va_approved': 0,
        'invoice_num': None,
        'asn_id': 2283,
        'project': 'Prj 315',
        'employee': 'WILLIAMS,THEODORE',
        'salary': 114786,
        'fringe': 35.2,
        'total_day': 594.89,
        'frum': '1912',
        'thru': '1912',
        'effort': 10,
        'days': 31,
        'amount': 1844.14,
        'paid': 0,
        'balance': 1844.14,
        'short_code': None,
        'grant_admin': None,
        'grant_admin_email': None
    }),
    Ledger({
        'id': None,
        'quarter': 20201,
        'dept': None,
        'admin_approved': 0,
        'va_approved': 0,
        'invoice_num': None,
        'asn_id': 2396,
        'project': 'Prj 315',
        'employee': 'BANKS,ERNEST',
        'salary': 44444,
        'fringe': 4.4,
        'total_day': 177.86,
        'frum': '1910',
        'thru': '1912',
        'effort': 20,
        'days': 92,
        'amount': 3272.65,
        'paid': 0,
        'balance': 3272.65,
        'short_code': None,
        'grant_admin': None,
        'grant_admin_email': None
    })
]

ledger_items_qtr_2 = [
    Ledger({
        'id': None,
        'asn_id': 2275,
        'employee': 'DIMAGGIO,JOSEPH P',
        'project': 'Prj 299',
        'quarter': 20202,
        'frum': '2002',
        'thru': '2003',
        'days': 60,
        'salary': 74971,
        'fringe': 43.9,
        'effort': 45,
        'total_day': 413.54,
        'amount': 11165.69,
        'paid': 0,
        'balance': 11165.69,
        'dept': None,
        'admin_approved': 0,
        'va_approved': 0,
        'grant_admin': None,
        'grant_admin_email': None,
        'invoice_num': None,
        'short_code': None,
    }),
    Ledger({
        'id': None,
        'asn_id': 2365,
        'employee': 'KALINE,ALBERT W',
        'project': 'Prj 309',
        'quarter': 20202,
        'frum': '2001',
        'thru': '2003',
        'days': 91,
        'salary': None,
        'fringe': None,
        'effort': 5,
        'total_day':  None,
        'amount': None,
        'paid': 0,
        'balance': None,
        'dept': None,
        'admin_approved': 0,
        'va_approved': 0,
        'grant_admin': None,
        'grant_admin_email': None,
        'invoice_num': None,
        'short_code': None
    }),
    Ledger({
        'id': None,
        'asn_id': 2375,
        'employee': 'AARON,HENRY',
        'project': 'Prj 309',
        'quarter': 20202,
        'frum': '2002',
        'thru': '2003',
        'days': 60,
        'salary': 74971,
        'fringe': 46.0,
        'effort': 15,
        'total_day': 419.58,
        'amount': 3776.21,
        'paid': 0,
        'balance': 3776.21,
        'dept': None,
        'admin_approved': 0,
        'va_approved': 0,
        'grant_admin': None,
        'grant_admin_email': None,
        'invoice_num': None,
        'short_code': None,
    }),
    Ledger({
        'id': None,
        'asn_id': 2382,
        'employee': 'MAYS,WILLIE HOWARD JR',
        'project': 'Prj 309',
        'quarter': 20202,
        'frum': '2002',
        'thru': '2002',
        'days': 29,
        'salary': 142052,
        'fringe': 31.7,
        'effort': 10,
        'total_day': 717.13,
        'amount': 2079.69,
        'paid': 0,
        'balance': 2079.69,
        'dept': None,
        'admin_approved': 0,
        'va_approved': 0,
        'grant_admin': None,
        'grant_admin_email': None,
        'invoice_num': None,
        'short_code': None,
    }),
    Ledger({
        'id': None,
        'asn_id': 2283,
        'employee': 'WILLIAMS,THEODORE',
        'project': 'Prj 315',
        'quarter': 20202,
        'frum': '2001',
        'thru': '2002',
        'days': 60,
        'salary': 114786,
        'fringe': 35.2,
        'effort': 10,
        'total_day':  594.89,
        'amount': 3569.31,
        'paid': 0,
        'balance': 3569.31,
        'dept': None,
        'admin_approved': 0,
        'va_approved': 0,
        'grant_admin': None,
        'grant_admin_email': None,
        'invoice_num': None,
        'short_code': None
    }),
    Ledger({
        'id': None,
        'asn_id': 2396,
        'employee': 'BANKS,ERNEST',
        'project': 'Prj 315',
        'quarter': 20202,
        'frum': '2001',
        'thru': '2003',
        'days': 91,
        'salary': 44444,
        'fringe': 4.4,
        'effort': 20,
        'total_day':  177.86,
        'amount': 3237.07,
        'paid': 0,
        'balance': 3237.07,
        'dept': None,
        'admin_approved': 0,
        'va_approved': 0,
        'grant_admin': None,
        'grant_admin_email': None,
        'invoice_num': None,
        'short_code': None
    }),
]

blank_details_form = {
    'dept': None,
    'admin_approved': False,
    'va_approved': False,
    'invoice_num': None,
    'salary': None,
    'fringe': None,
    'total_day': None,
    'days': None,
    'amount': None,
    'paid': False,
    'balance': None,
    'short_code': None,
    'grant_admin': None,
    'grant_admin_email': None
}
